#!/bin/bash

# Version: v0.2.0

# Copyright (c) 2014 Tristan Cavelier <t.cavelier@free.fr>
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# the COPYING file for more details.

cmd=$(basename "$0")
usage="Usage: $cmd [sdxx...]"

blkget() {
    local tmp=
    tmp=$(lsblk -rno "$1" "$2" | head -n 1) || return 2
    [ "$tmp" ] && echo "$tmp"
}

use_mount_unmount() {
    local id=
    id=$(blkget MOUNTPOINT "$1") || return 1
    umount "$id" || return 1
    rmdir "$id" || return 0
}

use_udisks_unmount() {
    udisks --unmount "$1"
}

use_udisks2_unmount() {
    udisksctl unmount -b "$1"
}

main () {
    [ $# = 0 ] && echo "$usage" && exec lsblk -f

    local um=
    local res=0

    # set unmount command
    if which udisksctl &>/dev/null ; then um=use_udisks2_unmount
    elif which udisks &>/dev/null ; then um=use_udisks_unmount
    elif which mount &>/dev/null ; then um=use_mount_unmount
    else echo "No unmount command found" >&2 ; return 2 ; fi

    # unmount
    for i in "$@" ; do
        $um /dev/"$i" || res=$?
    done

    return $res
}

main "$@"
