#!/bin/bash
# version 0.1.0 Tue 10 September 2013
# file: /usr/bin/um

#
# The MIT License (MIT)
#
# Copyright (c) 2013 Tristan Cavelier <t.cavelier@free.fr>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

# script using "udisks2", "udisks" or "mount"
# and "lsblk" and "lsof"

# This script shows or unmounts mounted devices/partitions
# type um --help for help

cmd="$0"

my_unmount() {
    local mountpoint=$(lsblk -rno MOUNTPOINT "$1")
    umount "$1" && rmdir "$mountpoint"
}

if which udisksctl &>/dev/null ; then
    udisksversion="udisks2"
    unmountcmd="udisksctl unmount -b"
elif which udisks &>/dev/null ; then
    udisksversion="udisks"
    unmountcmd="udisks --unmount"
else
    echo WARNING: No udisks program found >&2
    udisksversion="umount"
    unmountcmd="my_unmount"
fi

usage="Shows/Unmounts mounted using \"lsof\", \"$udisksversion\" and \"lsblk\".
Usage:   ${cmd} [options] [sdxy]
Example: ${cmd} sda3
         ${cmd} -a

Options list
   -h, --help
          Show this help and exit
   -a, --unmount-all
          Unmount all partitions.
"

unmount_all() {
    local devlist=$(lsblk -nro NAME,TYPE,MOUNTPOINT | \
        egrep "^[^ ]+ part /run/media/" | cut -d ' ' -f 1)
    local result=0
    test ! "$devlist" && return
    echo "$devlist" | while IFS= read -r dev ; do
        $unmountcmd "/dev/$dev"
        local res=$?
        if test $res != 0 ; then
            lsof | grep "$(lsblk -nro MOUNTPOINT /dev/$dev)"
        fi
        test $res -gt $result && result=$res
    done
    return $result
}

unmount_selected() {
    local result=0
    for dev in "$@" ; do
        $unmountcmd "/dev/$dev"
        local res=$?
        if test $res != 0 ; then
            lsof | grep "$(lsblk -nro MOUNTPOINT /dev/$dev)"
        fi
        test $res -gt $result && result=$res
    done
    return $result
}

main() {
    local unmountall=false
    local getoptret=
    getoptret=$(getopt -ul help,unmount-all ha "$@")
    test $? != 0 && echo "$usage" && exit 1
    eval set -- "$getoptret"
    while true ; do
        case "$1" in
            -a|--unmount-all)
                unmountall=true
                shift
                ;;
            -h|--help)
                exec echo "$usage"
                ;;
            --) shift ; break ;;
            *)  exit 2 ;;
        esac
    done

    if $unmountall ; then
        unmount_all
    elif test $# = 0 ; then
        lsblk -o NAME,FSTYPE,LABEL,UUID,MOUNTPOINT
        # lsblk -f
    else
        unmount_selected "$@"
    fi
}
main "$@"
